//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMRAH.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>ooo</string>
  <string>out of office</string>
  <string>oof</string>
  <string>out of facility</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection SubjectFilters {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["SubjectFilters"]));
            }
            set {
                this["SubjectFilters"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection RecipientFilters {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["RecipientFilters"]));
            }
            set {
                this["RecipientFilters"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UnlessDirect {
            get {
                return ((bool)(this["UnlessDirect"]));
            }
            set {
                this["UnlessDirect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Other OOF")]
        public string CategoryName {
            get {
                return ((string)(this["CategoryName"]));
            }
            set {
                this["CategoryName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("olCategoryColorGray")]
        public global::Microsoft.Office.Interop.Outlook.OlCategoryColor CategoryColor {
            get {
                return ((global::Microsoft.Office.Interop.Outlook.OlCategoryColor)(this["CategoryColor"]));
            }
            set {
                this["CategoryColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SendResponse {
            get {
                return ((bool)(this["SendResponse"]));
            }
            set {
                this["SendResponse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("olMeetingTentative")]
        public global::Microsoft.Office.Interop.Outlook.OlMeetingResponse Response {
            get {
                return ((global::Microsoft.Office.Interop.Outlook.OlMeetingResponse)(this["Response"]));
            }
            set {
                this["Response"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ClearReminder {
            get {
                return ((bool)(this["ClearReminder"]));
            }
            set {
                this["ClearReminder"] = value;
            }
        }
    }
}
